services:
  db:
    platform: linux/x86_64 # NOTE: M1の人はコメントイン
    container_name: db
    image: mysql:8.0.39
    env_file: ./.env/
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/data:/var/lib/mysql
    command: --default_authentication_plugin=mysql_native_password

  app:
    platform: linux/x86_64
    container_name: app
    build:
      context: ./docker/app
    volumes:
      - ./:/app
    env_file: ./.env/
    tty: true
    ports:
      - 8080:8080
    depends_on:
      - db